### ISSUE TITLE
Homepage CSS

### ISSUE THREAD

**Issue by Pranav-Patani** [Pranav-Patani/BookWise#7]
### Grid Layout
- [x] Set up a grid layout for the home page

### Header
- [x] Grid layout
- [x] Position buttons and logo
- [x] Sticky header

![image](https://github.com/Pranav-Patani/BookWise/assets/65628937/c5b500b6-8cc9-4e3e-abb8-90695c94c229)

### Hero
- [x] Grid Layout
- [x] Position Text and buttons on first cell
- [x] Position overlapping images on second cell
- [x] Slanting divider?

![image](https://github.com/Pranav-Patani/BookWise/assets/65628937/bc7e9ad8-2788-436a-985c-e720be32b02f)

### Section Find Books
- [x] Grid layout: 3 rows, 2nd row 2 columns -> 2nd column 4 rows
- [x] Position temporary video
- [x] Select svg icons and position with text
- [x] Heading and CTA button

![image](https://github.com/Pranav-Patani/BookWise/assets/65628937/a035de06-cf8f-4837-b42f-93ff410da8f6)

### Section Plan Recommendations
- [x] Grid layout: 5 rows, rows 2,3,4-> 2 columns
- [x] Position text and images, alternating text and images
- [x] Heading and CTA button

![image](https://github.com/Pranav-Patani/BookWise/assets/65628937/489a99cc-b19b-4940-9763-24bfb183ef5b)

### Footer
- [x] Grid Layout: 3 rows, 2nd row with 4 columns
- [x] Position logo
- [x] Select svg icons and create buttons for 2nd row

![image](https://github.com/Pranav-Patani/BookWise/assets/65628937/16835a0c-4dc7-4487-8907-17b5809d7cca)

**Comment by khusharth** [comment]
If the header is scrollable, do we need the same CTAs in footer again?
